SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `Exercises`;
DROP TABLE IF EXISTS `Sets`;
DROP TABLE IF EXISTS `Workout_Exercise`;
DROP TABLE IF EXISTS `Workouts`;
DROP TABLE IF EXISTS `Users`;
SET FOREIGN_KEY_CHECKS = 1;
